# Generated by Django 4.2.11 on 2025-05-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True, verbose_name='адрес')),
                ('lat', models.FloatField(null=True, verbose_name='широта')),
                ('lon', models.FloatField(null=True, verbose_name='долгота')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
        ),
    ]
