version: '3.12'

volumes:
  postgres_data:
  media_data:

services:
  backend:
    image: nastiaetstesha/star_burgers:backend
    restart: always
    volumes:
      - ./assets:/app/assets
      - ./bundles:/app/bundles 
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    image: nastiaetstesha/star_burgers:frontend
    restart: always
    volumes:
      - ./bundles:/app/bundles

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./staticfiles:/app/staticfiles:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./media:/app/media:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
  
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: burgers_dvm
      POSTGRES_USER: burgers_user
      POSTGRES_PASSWORD: 1234Qwer
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"