version: '3.12'

services:
  backend:
    image: nastiaetstesha/star_burgers:backend
    volumes:
      - ./assets:/app/assets
      - ./bundles:/app/bundles 
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    image: nastiaetstesha/star_burgers:frontend
    volumes:
      - ./bundles:/app/bundles

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./staticfiles:/app/staticfiles:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./media:/app/media:ro
    depends_on:
      - backend
  
  # db:
  #   image: postgres:15
  #   env_file:
  #     - .env
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data