# Generated by Django 4.2.11 on 2025-05-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_order_cooking_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Необработанный'), ('confirmed', 'Подтверждённый'), ('cooking', 'Готовится'), ('assembled', 'Собран'), ('delivering', 'В доставке'), ('completed', 'Завершён')], db_index=True, default='unprocessed', max_length=20, verbose_name='статус'),
        ),
    ]
