# Generated by Django 4.2.11 on 2025-05-05 19:10

from django.db import migrations


def fill_orderitem_prices(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')

    items = OrderItem.objects.filter(price__isnull=True).select_related('product')

    for item in items:
        item.price = item.product.price
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_orderitem'),
    ]

    operations = [
        migrations.RunPython(fill_orderitem_prices),
    ]
