# Generated by Django 4.2.11 on 2025-05-13 20:47

from django.db import migrations


def replace_null_comments(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    Order.objects.filter(comment__isnull=True).update(comment='')


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_alter_order_status'),
    ]

    operations = [
        migrations.RunPython(replace_null_comments),
    ]
